src/modules/logger/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <description>The custom object for storing debug information, errors, and integration request details. It allows administrators to capture and track critical data, facilitating efficient troubleshooting and analysis of system activities, errors, and external interactions within your Salesforce environment.</description>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{00000000}</displayFormat>
        <label>Log Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/modules/logger/objects/Log__c/fields/Context__c.field-meta.xml
<CustomField>
    <fullName>Context__c</fullName>
    <description>A generalized execution category for easier identification, consolidating detailed quiddities into broader types like Batch, Trigger, or Test.</description>
    <inlineHelpText>A generalized execution category for easier identification, consolidating detailed quiddities into broader types like Batch, Trigger, or Unit Test.</inlineHelpText>
    <label>Context</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ANONYMOUS</fullName>
                <label>Anonymous Apex</label>
            </value>
            <value>
                <fullName>API</fullName>
                <label>Integration</label>
            </value>
            <value>
                <fullName>BATCH</fullName>
                <label>Batch</label>
            </value>
            <value>
                <fullName>APEX_TRIGGER</fullName>
                <label>Trigger</label>
            </value>
            <value>
                <fullName>UI</fullName>
                <label>User Interface</label>
            </value>
            <value>
                <fullName>UNIT_TEST</fullName>
                <label>Unit Test</label>
            </value>
            <value>
                <fullName>OTHER</fullName>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/modules/logger/objects/Log__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>Indicates the severity or importance of the logged event, helping to categorize and prioritize logs</description>
    <inlineHelpText>Indicates the severity or importance of the logged event, helping to categorize and prioritize logs</inlineHelpText>
    <label>Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>10</fullName>
                <default>true</default>
                <label>DEBUG</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>INFO</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>WARNING</label>
            </value>
            <value>
                <fullName>40</fullName>
                <label>ERROR</label>
            </value>
            <value>
                <fullName>50</fullName>
                <label>CRITICAL</label>
            </value>
            <value>
                <fullName>60</fullName>
                <label>FATAL</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/modules/logger/objects/Logger_Settings__c/Logger_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Logger settings defining the main logging parameters.</description>
    <label>Logger Settings</label>
</CustomObject>

src/modules/logger/objects/Logger_Settings__c/fields/Is_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Is_Enabled__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates whether logging is active.</description>
    <inlineHelpText>Whether logging is enabled for a profile or a user selected in the Location field.</inlineHelpText>
    <label>Enabled</label>
    <type>Checkbox</type>
</CustomField>

src/sfinx/modules/logger/objects/Logger_Settings__c/fields/Min_Log_Level__c.field-meta.xml
<CustomField>
    <fullName>Min_Log_Level__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Minimum logging level. Numerical value.</description>
    <inlineHelpText>Minimum logging level. Numerical value (10 - Debug, 20 - Warning, 30 - Error, 40 - Fatal).</inlineHelpText>
    <label>Min Log Level</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/modules/logger/classes/LoggerTest.cls
/**
 * (c) Alexander Hooke <alexander.hooke@gmail.com>
 *
 * This file is part of the SFINX package. For the full copyright and license information,
 * please view the LICENSE file that was distributed with this source code.
 */
@IsTest
private class LoggerTest {

    @TestSetup
    static void makeData() {
        // Org Default Logger Settings
        insert new Logger_Settings__c(
            Is_Enabled__c = true,
            Min_Log_Level__c = 0
        );
    }

    @IsTest
    static void testDebug() {

        Logger.debug('Debug message');

        // Add assertions to check if the log record is created
        List<Log__c> logs = [SELECT Context__c, Level__c, Message__c FROM Log__c LIMIT 1000];
        Assert.areEqual(1, logs.size());

        Log__c log = logs[0];
        Assert.areEqual(String.valueOf(Logger.LEVEL_DEBUG), log.Level__c);
    }

    @IsTest
    static void testDebugWithObject() {

        Logger.debug('Debug message', new List<String>());

        // Add assertions to check if the log record is created
        List<Log__c> logs = [SELECT Context__c, Level__c, Message__c FROM Log__c LIMIT 1000];
        Assert.areEqual(1, logs.size());

        Log__c log = logs[0];
        Assert.areEqual(String.valueOf(Logger.LEVEL_DEBUG), log.Level__c);
    }

    @IsTest
    static void testDatabaseInsert() {

        Test.startTest();
        SObject[] records = new List<Account>{new Account()};
        Database.SaveResult[] saveResults = Database.insert(records, false);
        Logger.log(records, saveResults);
        Test.stopTest();

        // Add assertions to check if the log record is created
        List<Log__c> logs = [SELECT Context__c, Level__c, Message__c FROM Log__c LIMIT 1000];
        Assert.areEqual(1, logs.size());

        Log__c log = logs[0];
        Assert.areEqual(String.valueOf(Logger.LEVEL_ERROR), log.Level__c);
    }

    @IsTest
    static void testDatabaseUpsert() {

        Test.startTest();
        SObject[] records = new List<Account>{new Account()};
        Database.UpsertResult[] upsertResults = Database.upsert(records, false);
        Logger.log(records, upsertResults);
        Test.stopTest();

        // Add assertions to check if the log record is created
        List<Log__c> logs = [SELECT Context__c, Level__c, Message__c FROM Log__c LIMIT 1000];
        Assert.areEqual(1, logs.size());

        Log__c log = logs[0];
        Assert.areEqual(String.valueOf(Logger.LEVEL_ERROR), log.Level__c);
    }

    @IsTest
    static void testLogException() {

        // Code that may throw an exception
        Test.startTest();
        try {
            insert new Account();
        } catch (Exception e) {
            Logger.log(e);
        }
        Test.stopTest();

        // Add assertions to check if the log record is created
        List<Log__c> logs = [SELECT Context__c, Level__c, Message__c FROM Log__c LIMIT 1000];
        Assert.areEqual(1, logs.size());

        Log__c log = logs[0];
        Assert.areEqual(Logger.CONTEXT_UNIT_TEST, log.Context__c);
        Assert.areEqual(String.valueOf(Logger.LEVEL_ERROR), log.Level__c);
    }
    
    @isTest
    static void testLogExceptionWithObject() {

        Test.startTest();
        try {
            Integer result = 1 / 0;
        } catch (Exception e) {
            Logger.log(e, new Account());
        }
        Test.stopTest();
        
        List<Log__c> logs = [SELECT Context__c, Level__c, Message__c FROM Log__c LIMIT 1000];
        Assert.areEqual(1, logs.size());

        Log__c log = logs[0];
        Assert.areEqual(Logger.CONTEXT_UNIT_TEST, log.Context__c);
        Assert.areEqual(String.valueOf(Logger.LEVEL_ERROR), log.Level__c);
    }

    @IsTest
    static void testLogMessage() {

        Test.startTest();
        Logger.log(Logger.LEVEL_DEBUG, 'Test log message');
        Test.stopTest();

        List<Log__c> logs = [SELECT Context__c, Level__c, Message__c FROM Log__c LIMIT 1000];
        Assert.areEqual(1, logs.size());
    }
}